### ISSUE TITLE
GET a /buscar dá un error 500

### ISSUE THREAD

**Issue by davidpv** [mpijierro/devoogle#2]
Cuando accedes a **/buscar** retorna con un error **500**.

**Comment by mpijierro** [comment]
Hola @davidpv ,

¿podrías aportar algo más de información al respecto? Entorno en el que has hecho la búsqueda, traza, el log de errores...etc etc.

Gracias.

**Comment by davidpv** [comment]
Simplementes pegas en el chrome la ruta https://www.devoogle.com/buscar y salta el error 500 de laravel.

**Comment by mpijierro** [comment]
Esa url se corresponde con una petición POST. Si quieres que funcione como GET, debes incluir un parámetro con la búsqueda, por ejemplo:

https://www.devoogle.com/buscar?search=php

**Comment by davidpv** [comment]
Ya lo sé, pero te lo comento porque si es obligatorio que sea una peticion POST cuando accedes por GET debería redirigirte o dar un 404.  ;)

**Comment by davidpv** [comment]
O incluso mostrar una pantalla con una advertencia como que no han habido resultados.

**Comment by mpijierro** [comment]
Ah, me parece bien si. Para la próxima vez que "toque" el código lo modifico para que sea más amigable esa pantalla.

¡Gracias!
